version: '3.3'

services:
  uam_1:
    image: debian:bullseye-slim
    container_name: uam_1
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT}"
    ports:
      - "127.0.0.1:17100:17099"
      - "4160:4160"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4160

  uam_2:
    image: debian:bullseye-slim
    container_name: uam_2
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT}"
    ports:
      - "127.0.0.1:17101:17099"
      - "4161:4161"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4161
