version: '2.4'

services:
  uam_1:
    image: debian:bullseye-slim
    container_name: uam_1
    hostname: uam_1
    restart: unless-stopped
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam_1:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17100:17099"
      - "4160:4160"
    mem_limit: 6000m
    oom_kill_disable: true
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4160
      - NETLIMUP=10000
      - NETLIMDOWN=18000

  uam_2:
    image: debian:bullseye-slim
    container_name: uam_2
    hostname: uam_2
    restart: unless-stopped
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam_2:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17101:17099"
      - "4161:4161"
    mem_limit: 6000m
    oom_kill_disable: true
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4161
      - NETLIMUP=10000
      - NETLIMDOWN=18000

  uam_3:
    image: debian:bullseye-slim
    container_name: uam_3
    hostname: uam_3
    restart: unless-stopped
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam_3:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17102:17099"
      - "4162:4162"
    mem_limit: 6000m
    oom_kill_disable: true
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4162
      - NETLIMUP=10000
      - NETLIMDOWN=18000
