version: '2.4'

services:
  uam_extend_1:
    image: debian:bullseye-slim
    container_name: uam_extend_1
    hostname: uam_extend_1
    restart: unless-stopped
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam_extend_1:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17200:17099"
      - "4260:4260"
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4260
      - NETLIMUP=10000
      - NETLIMDOWN=18000
  
  uam_extend_2:
    image: debian:bullseye-slim
    container_name: uam_extend_2
    hostname: uam_extend_2
    restart: unless-stopped
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam_extend_2:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17201:17099"
      - "4261:4261"
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4261
      - NETLIMUP=10000
      - NETLIMDOWN=18000
 
  uam_extend_3:
    image: debian:bullseye-slim
    container_name: uam_extend_3
    hostname: uam_extend_3
    restart: unless-stopped
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam_extend_3:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17202:17099"
      - "4262:4262"
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4262
      - NETLIMUP=10000
      - NETLIMDOWN=18000
