version: '2.4'

services:
  uam:
    image: debian:bullseye-slim
    container_name: uam
    hostname: uam
    restart: always
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data/uam:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:18100:17099"
      - "4260:4260"
    environment:
      - PBKEY=${PBKEY?err}
      - PPORT=4260
      - NETLIMUP=10000
      - NETLIMDOWN=18000
